# Generated by Django 5.0 on 2025-07-24 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_consentrequest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='context',
            name='family',
            field=models.CharField(blank=True, max_length=120),
        ),
    ]
