# Generated by Django 5.0 on 2025-07-24 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_context_family'),
    ]

    operations = [
        migrations.AddField(
            model_name='context',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
