# Generated by Django 5.0 on 2025-07-25 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_profile_company_address_profile_company_country_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='is_public_profile',
            field=models.BooleanField(default=False, help_text='Make profile searchable and viewable by others'),
        ),
        migrations.AddField(
            model_name='profile',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pictures/'),
        ),
    ]
