# Generated by Django 5.0 on 2025-07-26 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_profile_is_public_profile_profile_profile_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='context',
            name='auto_archive_expired',
            field=models.BooleanField(default=False, help_text='Automatically archive when expired codes become invalid'),
        ),
        migrations.AddField(
            model_name='context',
            name='notify_on_redeem',
            field=models.BooleanField(default=True, help_text='Send notification when this context is redeemed'),
        ),
    ]
