# Generated by Django 5.0 on 2025-07-29 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_add_context_notification_settings'),
    ]

    operations = [
        migrations.AddField(
            model_name='context',
            name='archived',
            field=models.BooleanField(default=False, help_text='Context is archived and hidden from active lists'),
        ),
        migrations.AddField(
            model_name='context',
            name='archived_at',
            field=models.DateTimeField(blank=True, help_text='When the context was archived', null=True),
        ),
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('redemption', 'Code Redeemed'), ('consent_request', 'Consent Requested'), ('consent_approved', 'Consent Approved'), ('consent_denied', 'Consent Denied'), ('access_revoked', 'Access Revoked'), ('context_expired', 'Context Expired')], max_length=20),
        ),
    ]
