# Generated by Django 5.0 on 2025-09-09 12:09

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_add_context_expiration_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consentrequest',
            name='message',
            field=models.TextField(blank=True, help_text='Optional message from requester explaining why they need access (max 500 characters)', max_length=500),
        ),
        migrations.AlterField(
            model_name='context',
            name='family',
            field=models.CharField(blank=True, max_length=120, validators=[django.core.validators.RegexValidator(message='Family name can only contain letters, spaces, hyphens, and apostrophes. Max 120 characters.', regex="^[a-zA-Z\\s\\-\\']{0,120}$")]),
        ),
        migrations.AlterField(
            model_name='context',
            name='given',
            field=models.CharField(max_length=120, validators=[django.core.validators.RegexValidator(message='Given name can only contain letters, spaces, hyphens, and apostrophes. Max 120 characters.', regex="^[a-zA-Z\\s\\-\\']{1,120}$")]),
        ),
        migrations.AlterField(
            model_name='context',
            name='label',
            field=models.CharField(max_length=40, validators=[django.core.validators.RegexValidator(message='Label can only contain letters, numbers, spaces, hyphens, and underscores. Max 40 characters.', regex='^[a-zA-Z0-9\\s\\-_]{1,40}$')]),
        ),
        migrations.AlterField(
            model_name='profile',
            name='company_country',
            field=models.CharField(blank=True, max_length=100, validators=[django.core.validators.RegexValidator(message='Country can only contain letters, spaces, and hyphens. Max 100 characters.', regex='^[a-zA-Z\\s\\-]{1,100}$')]),
        ),
        migrations.AlterField(
            model_name='profile',
            name='company_founded',
            field=models.PositiveIntegerField(blank=True, help_text='Year company was founded (e.g., 1995)', null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='company_name',
            field=models.CharField(blank=True, max_length=200, validators=[django.core.validators.RegexValidator(message='Company name can contain letters, numbers, spaces, hyphens, ampersands, periods, apostrophes, and commas. Max 200 characters.', regex="^[a-zA-Z0-9\\s\\-\\&\\.\\'\\,]{1,200}$")]),
        ),
        migrations.AlterField(
            model_name='profile',
            name='company_phone',
            field=models.CharField(blank=True, max_length=20, validators=[django.core.validators.RegexValidator(message='Phone number must contain only digits, spaces, hyphens, parentheses, and optional plus sign. Length: 7-20 characters.', regex='^[+]?[0-9\\s\\-\\(\\)]{7,20}$')]),
        ),
        migrations.AlterField(
            model_name='profile',
            name='company_website',
            field=models.URLField(blank=True, validators=[django.core.validators.URLValidator(message='Please enter a valid URL (e.g., https://example.com)')]),
        ),
        migrations.AlterField(
            model_name='profile',
            name='country',
            field=models.CharField(blank=True, max_length=100, validators=[django.core.validators.RegexValidator(message='Country can only contain letters, spaces, and hyphens. Max 100 characters.', regex='^[a-zA-Z\\s\\-]{1,100}$')]),
        ),
        migrations.AlterField(
            model_name='profile',
            name='first_name',
            field=models.CharField(blank=True, max_length=50, validators=[django.core.validators.RegexValidator(message='First name can only contain letters, spaces, hyphens, and apostrophes. Max 50 characters.', regex="^[a-zA-Z\\s\\-\\']{1,50}$")]),
        ),
        migrations.AlterField(
            model_name='profile',
            name='last_name',
            field=models.CharField(blank=True, max_length=50, validators=[django.core.validators.RegexValidator(message='Last name can only contain letters, spaces, hyphens, and apostrophes. Max 50 characters.', regex="^[a-zA-Z\\s\\-\\']{1,50}$")]),
        ),
        migrations.AlterField(
            model_name='profile',
            name='phone',
            field=models.CharField(blank=True, max_length=20, validators=[django.core.validators.RegexValidator(message='Phone number must contain only digits, spaces, hyphens, parentheses, and optional plus sign. Length: 7-20 characters.', regex='^[+]?[0-9\\s\\-\\(\\)]{7,20}$')]),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=254, validators=[django.core.validators.EmailValidator(message='Please enter a valid email address')], verbose_name='email address'),
        ),
    ]
