# Generated by Django 5.0 on 2025-09-09 12:28

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_alter_user_managers_alter_consentrequest_message_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='company_phone',
            field=models.CharField(blank=True, max_length=20, validators=[django.core.validators.RegexValidator(message='Phone number can only contain numbers, spaces, hyphens, parentheses, and plus sign.', regex='^[+]?[0-9\\s\\-\\(\\)]{7,20}$')]),
        ),
        migrations.AlterField(
            model_name='profile',
            name='phone',
            field=models.CharField(blank=True, max_length=20, validators=[django.core.validators.RegexValidator(message='Phone number can only contain numbers, spaces, hyphens, parentheses, and plus sign.', regex='^[+]?[0-9\\s\\-\\(\\)]{7,20}$')]),
        ),
    ]
