# Generated by Django 5.0 on 2025-09-09 12:51

import phonenumber_field.modelfields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_alter_profile_company_phone_alter_profile_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='company_phone',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, help_text='Enter company phone number with country code', max_length=128, region=None),
        ),
        migrations.AlterField(
            model_name='profile',
            name='phone',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, help_text='Enter phone number with country code', max_length=128, region=None),
        ),
    ]
