# Generated by Django 5.0 on 2025-09-16 18:26

from django.db import migrations, models


def clean_duplicate_sharecodes(apps, schema_editor):
    """
    Clean up duplicate non-revoked ShareCodes for the same context.
    Keep the most recent one and revoke the others.
    """
    ShareCode = apps.get_model('api', 'ShareCode')
    Context = apps.get_model('api', 'Context')

    for context in Context.objects.all():

        non_revoked_codes = ShareCode.objects.filter(
            context=context,
            revoked=False
        ).order_by('-id')

        if non_revoked_codes.count() > 1:

            codes_to_revoke = non_revoked_codes[1:]
            for code in codes_to_revoke:
                code.revoked = True
                code.save()


def reverse_clean_duplicate_sharecodes(apps, schema_editor):
    """
    Reverse operation - this is not reversible, so we do nothing
    """
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_alter_profile_company_phone_alter_profile_phone'),
    ]

    operations = [

        migrations.RunPython(
            clean_duplicate_sharecodes,
            reverse_clean_duplicate_sharecodes
        ),

        migrations.AddConstraint(
            model_name='sharecode',
            constraint=models.UniqueConstraint(
                fields=['context'],
                condition=models.Q(revoked=False),
                name='unique_active_sharecode_per_context'
            ),
        ),
    ]
