# Generated by Django 5.0 on 2025-09-16 19:09

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_add_unique_constraint_sharecode'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='sharecode',
            name='unique_active_sharecode_per_context',
        ),
        migrations.AlterField(
            model_name='context',
            name='family',
            field=models.CharField(blank=True, max_length=120, validators=[api.models.validate_name_chars]),
        ),
        migrations.AlterField(
            model_name='context',
            name='given',
            field=models.CharField(max_length=120, validators=[api.models.validate_name_chars]),
        ),
        migrations.AlterField(
            model_name='context',
            name='label',
            field=models.CharField(max_length=40, validators=[api.models.validate_context_label_chars]),
        ),
        migrations.AlterField(
            model_name='profile',
            name='company_country',
            field=models.CharField(blank=True, max_length=100, validators=[api.models.validate_country_chars]),
        ),
        migrations.AlterField(
            model_name='profile',
            name='company_name',
            field=models.CharField(blank=True, max_length=200, validators=[api.models.validate_company_name_chars]),
        ),
        migrations.AlterField(
            model_name='profile',
            name='country',
            field=models.CharField(blank=True, max_length=100, validators=[api.models.validate_country_chars]),
        ),
        migrations.AlterField(
            model_name='profile',
            name='first_name',
            field=models.CharField(blank=True, max_length=50, validators=[api.models.validate_name_chars]),
        ),
        migrations.AlterField(
            model_name='profile',
            name='last_name',
            field=models.CharField(blank=True, max_length=50, validators=[api.models.validate_name_chars]),
        ),
    ]
