# Generated by Django 5.0 on 2025-09-16 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_add_revoked_to_audit'),
    ]

    operations = [
        migrations.AddField(
            model_name='audit',
            name='revoked',
            field=models.BooleanField(default=False),
        ),
    ]
