# Generated by Django 5.0 on 2025-09-16 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0021_add_revoked_field_to_audit'),
    ]

    operations = [
        migrations.AddField(
            model_name='context',
            name='expiration_processed',
            field=models.BooleanField(default=False),
        ),
    ]
